### ISSUE TITLE
Is is for Japanese rule?

### ISSUE THREAD

**Issue by chengr4** [lightvector/goscorer#1]
Hi,

I accidentally saw this cool project and was curious whether it is for Japanese rule? As i saw the `komi= 6.5`

**Comment by lightvector** [comment]
Yes, this attempts to do territory scoring without counting points in seki, which corresponds to the Japanese rules often played on online servers. Note that this is not the same as *strict* Japanese rules - for example Japanese rules technically require you to fill all the dame before ending the game, even though this is almost never done on online servers.

**Comment by chengr4** [comment]
Thanks for replying! Because I know how hard to implement scoring, I have infinite respect for you.

Only one small suggestion:
Perhaps, at some point in the future, you can tell users in the README about which rules of Japanese are included and which are not supported.
